Simplified text coloring

diff --git a/amalgamate b/amalgamate
--- a/amalgamate
+++ b/amalgamate
@@ -7,22 +7,17 @@
 
 SCRIPT_NAME=$(basename $0)
 
-TS_N='\e[0m'
-TEXT_STYLE_ERROR='\e[0;31m'
-TS_B='\e[1m'
-TS_U='\e[4m'
-
-ERROR_STYLE_BEGIN=''
-ERROR_STYLE_END=''
-if [[ -t 1 ]] && [[ $(tput colors) > 0 ]]
+if [[ -t 1 ]] && (( $(tput colors) > 0 ))
 then
-	ERROR_STYLE_BEGIN="$TEXT_STYLE_ERROR"
-	ERROR_STYLE_END="$TS_N"
+	TS_N='\e[0m'
+	TS_RED='\e[0;31m'
+	TS_B='\e[1m'
+	TS_U='\e[4m'
 fi
 
 printf-error()
 {
-	printf "$ERROR_STYLE_BEGIN$SCRIPT_NAME error:$ERROR_STYLE_END " >&2
+	printf "$TS_RED$SCRIPT_NAME error:$TS_N " >&2
 	printf "$@" >&2
 	printf '\n' >&2
 }
